config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'movies#index'

  resources :movies,  param: :imdbID,  only: [:index, :show] do
    collection do
      get 'search'
      post 'add_to_favorites'
      get 'view_favorites'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord

    def self.thumbnail(poster)
        if poster.present? && poster != 'N/A' 
            return poster
        else
            "https://m.media-amazon.com/images/M/MV5BYTYxMzg2ZGUtY2VhMS00YWFmLWE3MjItOTZhYTQ1MGU3YjEyXkEyXkFqcGdeQXVyMTEzNzg0Mjkx._V1_SX300.jpg"
        end
    end


    def self.create_entry(params)
        Movie.create(imdbID: params["imdbID"],
                    title: params["Title"],
                    poster: params["Poster"],
                    movie_type: params["Type"],
                    year: params["Year"],
                    favorite: true)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_omdb_service, only: [:index, :search, :show, :add_to_favorites]
  
    def index
      @movies = @omdb_service.search_movies('2023')
    end
  
    def search
      @movies = @omdb_service.search_movies(params[:query])
      render :index
    end
  
    def show
      @movie = @omdb_service.get_movie_details(params[:imdbID])
    end
  
    def add_to_favorites
      @movie = Movie.find_by_imdbID(params["imdbID"])
      if @movie
        @movie.favorite = true
        @movie.save
        flash.now[:success] = "Movie added to favorites"
      else 
        @movie = Movie.create_entry(params)
        flash.now[:success] = "Movie added to favorites"
      end
    end

    def view_favorites
      @movies = Movie.where(favorite: true)
    end

    private
  
    def set_omdb_service
      @omdb_service = OmdbService.new(ENV['OMDB_API_KEY'])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'movies', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="header">
  <h1>Movies</h1>
  <%= button_to 'View Favorites', { controller: 'movies', action: 'view_favorites' }, method: :get, class: 'fav-btn' %>
</div>




<div class="search-box">
  <%= form_tag(search_movies_path, method: :get) do %>
    <%= text_field_tag :query, params[:query], placeholder: 'Search movies...' %>
    <%= submit_tag 'Search', class: 'search-btn' %>
  <% end %>
</div>

<ul class="movies-list">
  <% @movies.each do |movie| %>
    <li class="movie-item">
      <%= link_to movie_path(movie["imdbID"]) do %>
        <%= image_tag(Movie.thumbnail(movie["Poster"]), alt: movie["Title"], class: 'thumbnail') %>
      <% end %>
      <div class="movie-details">
        <h3><%= link_to "#{movie["Title"]} (#{movie["Year"]})", movie_path(movie["imdbID"]) %></h3>
        <%= button_to 'Add to Favorites', { controller: 'movies', action: 'add_to_favorites', id: movie["imdbID"], params: movie }, method: :post, class: 'add-fav' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/movies/show.html.erb
<div class="header">
    <h1><%= @movie["Title"] %> (<%= @movie["Year"] %>)</h1>
    <%= button_to 'Back to Movies', { controller: 'movies', action: 'index' }, method: :get, class: 'back-btn' %>
</div>
<div class="movie-details">
  

  <div class="movie-info">
    <%= image_tag(@movie["Poster"], alt: @movie["Title"], class: 'movie-poster') if @movie["Poster"].present? %>

    <div class="details">
      <p><strong>Plot:</strong> <%= @movie["Plot"] %></p>
      <p><strong>Genre:</strong> <%= @movie["Genre"] %></p>
      <p><strong>Director:</strong> <%= @movie["Director"] %></p>
      <p><strong>Actors:</strong> <%= @movie["Actors"] %></p>
      <p><strong>Awards:</strong> <%= @movie["Awards"] %></p>
      <p><strong>Country:</strong> <%= @movie["Country"] %></p>
      <p><strong>Released:</strong> <%= @movie["Released"] %></p>
      <p><strong>Language:</strong> <%= @movie["Language"] %></p>
    </div>
  </div>

  <%= button_to 'Add to Favorites', { controller: 'movies', action: 'add_to_favorites', id: @movie["imdbID"], params: @movie }, method: :post, class: 'add-fav' %>

</div>

app/views/movies/view_favorites.html.erb
<div class="header">
    <h1>Favorite Movies</h1>
    <%= button_to 'Back to Movies', { controller: 'movies', action: 'index' }, method: :get, class: 'back-btn' %>
</div>

<ul class="movies-list">
  <% @movies.each do |movie| %>
    <li class="movie-item">
      <%= link_to movie_path(movie.imdbID) do %>
        <%= image_tag(Movie.thumbnail(movie.poster), alt: movie.title, class: 'thumbnail') %>
      <% end %>
      <div class="movie-details">
        <h3><%= link_to "#{movie.title} (#{movie.year})", movie_path(movie["imdbID"]) %></h3>
      </div>
    </li>
  <% end %>
</ul>